ros2_camera_lidar_fusion:
  ros__parameters:
    lidar:
      #lidar_topic: /obstacle_point_cloud
      lidar_topic: /left_laser/pandar
      colored_cloud_topic: /rgb_cloud

    camera:
      image_topic: /segmentation/image
      confidence_topic: /segmentation/confidence
      projected_topic: /projected_image

    chessboard:
      pattern_size:
        rows: 7
        columns: 9
      square_size_meters: 0.41

    general:
      camera_intrinsic_calibration: ~/ros2_ws/src/ros2_camera_lidar_fusion/param/intrinsics.yaml
      
      slop: 0.1
      max_file_saved: 10
      keyboard_listener: True
      get_intrinsics: True
      get_extrinsics: True