ros2_camera_lidar_fusion:
  ros__parameters:
    lidar:
      #lidar_topic: /obstacle_point_cloud
      #lidar_topic: /livox/lidar_192_168_100_116
      lidar_topic: /front_os/points
      colored_cloud_topic: /rgb_cloud

    camera:
      image_topic: /segmentation/image
      confidence_topic: /segmentation/confidence
      projected_topic: /projected_image

    chessboard:
      pattern_size:
        rows: 7
        columns: 9
      square_size_meters: 0.41

    general:
      camera_intrinsic_calibration: ~/semantic_ws/src/ros2_camera_lidar_fusion/param/warthog.yaml
      
      slop: 0.12
      max_queue_size: 10