lidar_camera_projection:
  ros__parameters:
    lidar:
      #lidar_topic: /obstacle_point_cloud
      lidar_topic: /left_laser/pandar
      colored_cloud_topic: /rgb_cloud
      frame_id: left_laser_mount

    camera:
      image_topic: /segmentation/image
      projected_topic: /projected_image
      image_size:
        width: 1280
        height: 720
      frame_id: hazard_front_left_camera_optical_frame

    chessboard:
      pattern_size:
        rows: 7
        columns: 9
      square_size_meters: 0.41

    general:
      config_folder: ~/ros2_ws/src/ros2_camera_lidar_fusion/config
      #camera_intrinsic_calibration: /home/robolab/ros2_ws/src/ros2_camera_lidar_fusion/param/fwt_intrinsics.yaml
      #camera_extrinsic_calibration: /home/robolab/ros2_ws/src/ros2_camera_lidar_fusion/param/fwt_extrinsics.yaml
      camera_intrinsic_calibration: /home/robolab/ros2_ws/src/ros2_camera_lidar_fusion/param/intrinsics.yaml
      camera_extrinsic_calibration: /home/robolab/ros2_ws/src/ros2_camera_lidar_fusion/param/extrinsics.yaml
      
      slop: 0.1
      max_file_saved: 10
      keyboard_listener: True
      get_intrinsics: True
      get_extrinsics: True